### ISSUE TITLE
Sample app - add demos for writing to database

### ISSUE THREAD

**Issue by adamstephensen** [SSWConsulting/SSW.DataOnion2#10]
A lot of the power of Data Onion comes in during database writes.

Please supply demos on the sample app for database create, updates and deletes across all the supported scenarios.

Suggestion: 

1. Create two new controllers: 
 - UnitOfWorkDemoController
 - DbContextDemoController

2. Move the Schools() and Schools2() methods from the current home controller to the correct new controller and rename to GetSchoolList()

3. Add a method to each of the demo controllers that demonstrates Create, Update and Delete

**Comment by fenix2222** [comment]
Completed as part of https://github.com/SSWConsulting/SSW.DataOnion2/pull/12
