### ISSUE TITLE
Dependency SSW.Dataonion.Interfaces alpha 4 is not in nuget

### ISSUE THREAD

**Issue by ronovelo** [SSWConsulting/SSW.DataOnion2#14]
When I want use SSW.DataOnion Visual Studio shows this error: The dependency  SSW.Dataonion.Interfaces >= 1.0.0-alpha-4 could not be resolveld. 

![image](https://cloud.githubusercontent.com/assets/15477594/14835970/89d211ae-0bd2-11e6-998a-70f17107fc12.png)

If I go to nuget package site, I can only see 1.0.0-alpha-1: [https://www.nuget.org/packages/SSW.DataOnion.Interfaces/](url)

**Comment by ronovelo** [comment]
Same problem with SSW.DataOnion.CodeGenerator

**Comment by fenix2222** [comment]
looks like we haven't release alpha-4, I will do it later tonight and will let you know

**Comment by fenix2222** [comment]
Hi @ronovelo,

I have published alpha-4 to nuget. Can you give it a try now: https://www.nuget.org/packages/SSW.DataOnion.Interfaces/1.0.0-alpha-4

**Comment by ronovelo** [comment]
Great now works DependencyResolution package. Thanks!

But SSW.DataOnion.CodeGenerator throws these errors:

![image](https://cloud.githubusercontent.com/assets/15477594/14853443/2d6ae56a-0c51-11e6-89a2-d1ab40e9f45a.png)

**Comment by fenix2222** [comment]
@ronovelo this is because code generator works with new dnx451 and dnxcore5 frameworks, you are trying to run it with net451

**Comment by ronovelo** [comment]
Ok, you are right. Thanks!
