### ISSUE TITLE
Method GetChangedEntities not implemented

### ISSUE THREAD

**Issue by ronovelo** [SSWConsulting/SSW.DataOnion2#15]
Method 'GetChangedEntities' in type 'SSW.DataOnion.Core.DbContextScope' of assembly 'SSW.DataOnion.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' has no implementation.

![image](https://cloud.githubusercontent.com/assets/15477594/14921426/d010328c-0df7-11e6-9bf2-0300b162df31.png)

Im using SSW.DataOnion.Core-alpha-5.0.0. In last version of github source code, method 'GetChangedEntities' is implemented, maybe is good idea release new versions of assemblies in Nuget.

Thanks.

**Comment by fenix2222** [comment]
@ronovelo I have updated all packages (Core and DependencyResolution.Microsoft) by one version up. Can you please try the latest, looks like those package versions got out of sync. Let me know if it works.

**Comment by ronovelo** [comment]
It's working! Thanks.
