### ISSUE TITLE
How pluralize tables?

### ISSUE THREAD

**Issue by ronovelo** [SSWConsulting/SSW.DataOnion2#17]
Is there a way to pluralize table names in Configurations classes??

Example:

```
public class DepartmentConfigurations : IEntityTypeConfiguration<Department>
    {
        public void Map(EntityTypeBuilder<Department> builder)
        {
            builder.HasKey(m => m.Id);
        }
    }
```

Where I can configure table name? I don't want to use DataAnnotations and my OnModelCreating method in DbContext is created by CodeGenerator.

Thanks in advance

**Comment by fenix2222** [comment]
Sure, just use builder.ToTable("xxx").

http://ef.readthedocs.io/en/latest/modeling/relational/tables.html#fluent-api

**Comment by ronovelo** [comment]
Hi, thanks for your answer but unfortunately method ToTable doesn't exist:

![image](https://cloud.githubusercontent.com/assets/15477594/15051567/ea831dc0-12be-11e6-9cc7-3ff00a794743.png)

**Comment by fenix2222** [comment]
@ronovelo It does exist, add this using statement to the top 

`using Microsoft.Data.Entity;`

Also, make sure that you have

`"EntityFramework.Relational": "7.0.0-rc1-final"` package in your package.json

**Comment by ronovelo** [comment]
Thank you so much, it works with using statement. Greetings!

**Comment by fenix2222** [comment]
@ronovelo Would you be able to share your email address. I want to email you few questions and it doens't really belong in this issue?

**Comment by ronovelo** [comment]
Ok, I sent you a mail.
