### ISSUE TITLE
Bring sswDataOnion to dotNet 4.6.1 ?

### ISSUE THREAD

**Issue by HighCow** [SSWConsulting/SSW.DataOnion2#18]
Hi there,

is there anyone working on to bring the NuGet Packages to FW V4.6.1?

My target is to use sswDataOnion for a ASP.NET Core (FW 4.6.1) frontend app with layer library projects based on V4.6.1
If I don't miss a page at the user giude, currently there is not option for that scenario.

Is it possible and desirable to do this by my self and bring that back via pull request?

regards
Heiko

**Comment by fenix2222** [comment]
Hi Heiko,

Sorry for a delayed reply. I have upgraded data onion to .NET Core 1.0 RTM and also added support for net451, net452, net 461 and core. You are welcome to do pull requests.

**Comment by fenix2222** [comment]
Hi Heiko,

Sorry for a delayed reply. I have upgraded data onion to .NET Core 1.0 RTM
and also added support for net451, net452, net 461 and core. You are
welcome to do pull requests.

On Fri, Jul 1, 2016 at 2:48 AM, HighCow <notifications@github.com> wrote:

> Hi there,
>
> is there anyone working on to bring the NuGet Packages to FW V4.6.1?
>
> My target is to use sswDataOnion for a ASP.NET Core (FW 4.6.1) frontend
> app with layer library projects based on V4.6.1
> If I don't miss a page at the user giude, currently there is not option
> for that scenario.
>
> Is it possible and desirable to do this by my self and bring that back via
> pull request?
>
> regards
> Heiko
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/SSWConsulting/SSW.DataOnion2/issues/18>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/AGWS9NIzQiB4TvKmhUW5wnQeo_bjOWQ9ks5qQ_NzgaJpZM4JCW_m>
> .
>



-- 
Kind Regards,

Igor Goldobin
Microsoft Certified Professional Developer
MInfTech, BEng, BIT, MCPD
Custom Web Design, IT Consulting, Enterprise Systems
Phone: 0409 096 917
Email:  igor.goldobin@gmail.com
Visit my website: www.e-fenix.com

**Comment by HighCow** [comment]
Hi Igor,

many thanks for that prompt replay and the code update. I will try to use it today.

regards
Heiko
