### ISSUE TITLE
Many Database(same structure)  with connection string 

### ISSUE THREAD

**Issue by elesh9** [SSWConsulting/SSW.DataOnion2#21]
I have many database(same structure) in my application at run time application allow to select which database open for the business work like Multi-Tenancy. So my question is how to inject  connection string in '**AddDataOnion**'  with **AutoFac**   after selection of database. 

Thanks.

**Comment by fenix2222** [comment]
There are few ways of doing in. Here is a proposed solution:

1. Make your static Autofac Container accessible from other parts of application
2. Once you know your connection string, create new Autofac builder, register IDbContextFactory and update existing container

```
var updater = new ContainerBuilder();
var dbContextConfigs = new [] {
    new DbContextConfig(yourNewConnectionString, typeof(MyDbContext), optionalInitializerIfNeeded)
};
updater.RegisterType<DbContextFactory>()
                .As<IDbContextFactory>()
                .WithParameter("dbContextConfigs", dbContextConfigs);

newBuilder.Update(yourExistingContainer);
```

**Comment by elesh9** [comment]
thanks for your reply, i already did this 
but  after read this  discussion  at Autofac repository  ContainerBuilder.Update  marked as Obsolete in feature check [https://github.com/autofac/Autofac/issues/811](url)

thanks again
