### ISSUE TITLE
Sample app - home page & layout tidy up

### ISSUE THREAD

**Issue by adamstephensen** [SSWConsulting/SSW.DataOnion2#9]
The sample app works great but would be better if 

1. remove the out of the box content. It is just noise
2. on the start page, include the links to the two relevant menu items and an explanation of what they are and the difference between them. (this should include a link to the readme.md of the project where the different strategies should be discussed)
    e.g. 'Schools - Using Unit of Work' & 'Schools - Using DbContext;'

**Comment by fenix2222** [comment]
Completed as part of https://github.com/SSWConsulting/SSW.DataOnion2/pull/12
